spring.application.name=despacho
server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3307/despacho_bd?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

microservices.pedidos.url=http://localhost:8086/api/pedidos
microservices.clientes.url=http://localhost:8082/api/v1/clientes
microservices.sucursales.url=http://localhost:8083/api/v1/sucursales
